src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $price_promo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Images", mappedBy="article", cascade={"persist"}, orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price_global;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $promo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $wordKey;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Boutique", inversedBy="article")
     */
    private $boutique;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Votes", mappedBy="article", orphanRemoval=true)
     */
    private $votes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Votes", mappedBy="votearticle", orphanRemoval=true)
     */
    private $votesarticle;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Cart", mappedBy="articles", orphanRemoval=true)
     */
    private $carts;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sous_category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $referency;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $slide;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $externalDetail;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->votes = new ArrayCollection();
        $this->votesarticle = new ArrayCollection();
        $this->carts = new ArrayCollection();
        $this->price=0;
        $this->price_global=0;
        $this->price_promo=0;
        $this->slide = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPricePromo(): ?int
    {
        return $this->price_promo;
    }

    public function setPricePromo(int $price_promo): self
    {
        $this->price_promo = $price_promo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }

    public function getPriceGlobal(): ?int
    {
        return $this->price_global;
    }

    public function setPriceGlobal(?int $price_global): self
    {
        $this->price_global = $price_global;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(?string $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPromo(): ?string
    {
        return $this->promo;
    }

    public function setPromo(string $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getWordKey(): ?string
    {
        return $this->wordKey;
    }

    public function setWordKey(?string $wordKey): self
    {
        $this->wordKey = $wordKey;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBoutique(): ?Boutique
    {
        return $this->boutique;
    }

    public function setBoutique(?Boutique $boutique): self
    {
        $this->boutique = $boutique;

        return $this;
    }

    /**
     * @return Collection|Votes[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Votes $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setArticle($this);
        }

        return $this;
    }

    public function removeVote(Votes $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getArticle() === $this) {
                $vote->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Votes[]
     */
    public function getVotesarticle(): Collection
    {
        return $this->votesarticle;
    }

    public function addVotesarticle(Votes $votesarticle): self
    {
        if (!$this->votesarticle->contains($votesarticle)) {
            $this->votesarticle[] = $votesarticle;
            $votesarticle->setVotearticle($this);
        }

        return $this;
    }

    public function removeVotesarticle(Votes $votesarticle): self
    {
        if ($this->votesarticle->contains($votesarticle)) {
            $this->votesarticle->removeElement($votesarticle);
            // set the owning side to null (unless already changed)
            if ($votesarticle->getVotearticle() === $this) {
                $votesarticle->setVotearticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->addArticle($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self
    {
        if ($this->carts->contains($cart)) {
            $this->carts->removeElement($cart);
            $cart->removeArticle($this);
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getSousCategory(): ?string
    {
        return $this->sous_category;
    }

    public function setSousCategory(?string $sous_category): self
    {
        $this->sous_category = $sous_category;

        return $this;
    }

    public function getReferency(): ?string
    {
        return $this->referency;
    }

    public function setReferency(string $referency): self
    {
        $this->referency = $referency;

        return $this;
    }

    public function getSlide(): ?int
    {
        return $this->slide;
    }

    public function setSlide(?int $slide): self
    {
        $this->slide = $slide;

        return $this;
    }

    public function getExternalDetail(): ?string
    {
        return $this->externalDetail;
    }

    public function setExternalDetail(?string $externalDetail): self
    {
        $this->externalDetail = $externalDetail;

        return $this;
    }
}

src/Entity/Votes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VotesRepository")
 */
class Votes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $value;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="votes")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="votes")
     */
    private $article;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="votesarticle")
     */
    private $votearticle;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Blog", inversedBy="votes")
     */
    private $blog;

    /**
     * @ORM\ManyToOne(targetEntity=Boutique::class, inversedBy="votes")
     */
    private $boutique;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="votes")
     */
    private $comments;
    
    public function __construct()
    {
        $this->created_at= new \DateTime();
        $this->comments = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getVotearticle(): ?Article
    {
        return $this->votearticle;
    }

    public function setVotearticle(?Article $votearticle): self
    {
        $this->votearticle = $votearticle;

        return $this;
    }

    public function getBlog(): ?Blog
    {
        return $this->blog;
    }

    public function setBlog(?Blog $blog): self
    {
        $this->blog = $blog;

        return $this;
    }

    public function getBoutique(): ?Boutique
    {
        return $this->boutique;
    }

    public function setBoutique(?Boutique $boutique): self
    {
        $this->boutique = $boutique;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setVotes($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getVotes() === $this) {
                $comment->setVotes(null);
            }
        }

        return $this;
    }
}

src/Form/BoutiqueType.php
<?php

namespace App\Form;

use App\Entity\Boutique;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BoutiqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la boutique',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('address', TextType::class, [
                'label' => 'Adresse',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => "Votre adresse"
                ]
            ])
            ->add('link', TextType::class, [
                'label' => 'Lien Fb de la boutique',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => "http://www.facebook.com"
                ]
            ])
            ->add('slogan', TextType::class, [
                'label' => 'Votre slogan',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => "Votre slogan"
                ]
            ])
            ->add('externalLink', TextType::class, [
                'label' => 'Lien externe ',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => "http://www.monSite.com"
                ]
            ])
            ->add('mail', EmailType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('contact', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])

            ->add('resume', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('apropos', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('image', FileType::class, [
                'label' => 'Logo',
                'required' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'required' => false,
                    'class' => 'form-control file'
                ]
            ])
            ->add('cover', FileType::class, [
                'label' => 'Couverture',
                'required' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'required' => false,
                    'class' => 'form-control'
                ]
            ])
            ->add('coverOther', FileType::class, [
                'label' => 'Couverture page autre',
                'required' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'required' => false,
                    'class' => 'form-control'
                ]
            ])
            ->add('coverContrib', FileType::class, [
                'label' => 'Couverture page contributeur',
                'required' => true,
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'required' => false,
                    'class' => 'form-control'
                ]
            ])
            ->add('user_condition', CKEditorType::class, [

                'input_sync' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Boutique::class,
        ]);
    }
}

templates/boutique/dependancies/_add_review.html.twig
{% if users['isComment'] %}
		<div id="review-form">
			<form id="{{ article.id }}" class="review-form review-form-article edit-review-form">
				<input name="id-vote" value="{{users['id']}}" type="hidden"/>
				<div class="input-rating">
					<span>Votre satisfaction :
					</span>
					<br>
					<div class="myvoting">
						{{my_vote_twig(users['value'], true)}}
					</div>
					    <textarea class="input comment" placeholder="Commentaire">{{users['comment']}}</textarea>					
				</div>
					<button class="js-delete-vote secondary-btn" data-id="{{users['id']}}">Supprimer</button>
					<button class="primary-btn btn-submit">Enregistrer</button>
			</form>

		</div>
{% elseif app.user %}
	
		<div id="review-form">
			<form id="{{ article.id }}" class="review-form review-form-article">
				<div class="input-rating">
					<span>Votre satisfaction :
					</span>
					<br>
					<div class="stars">
						<input id="star5" name="rating" value="5" type="radio"><label for="star5"></label>
						<input id="star4" name="rating" value="4" type="radio"><label for="star4"></label>
						<input id="star3" name="rating" value="3" type="radio"><label for="star3"></label>
						<input id="star2" name="rating" value="2" type="radio"><label for="star2"></label>
						<input id="star1" name="rating" value="1" type="radio"><label for="star1"></label>
					</div>
					<textarea class="input comment" placeholder="Commentaire" required></textarea>
				</div>
				<button class="primary-btn btn-submit">Enregistrer</button>
			</form>
		</div>
{% endif %}

templates/boutique/dependancies/_cartforboutique.html.twig
<div class="col-md-4 col-xs-6">
    <div class="product">
        <a href="{{path('detail',{'id' : article.id,'slug' : article.name|slug('-')|lower})}}">
            <div class="product-img">
                <img src="{{asset('images/'~article.images[0].name)}}" alt="">
                {#<div id="_action_for_cart" class="product-btns">
                    <button class="add-to-wishlist"><i class="fa fa-heart-o"></i></button>
                    <button class="add-to-compare"><i class="fa fa-shopping-cart"></i></button>
                    <button class="quick-view"><i class="fa fa-eye"></i></button>
                </div>
                #}
            </div>
        </a>
        <div class="product-body">
            <div class="product-rating">
                {{ my_vote_twig(article.votes) }}
            </div>
            <p class="product-category">#{{article.category}}</p>
            <h3 class="product-name"><a href="#">{{article.name}}</a></h3>
            <h4 class="product-price">{{article.price| number_format(0,',',' ') }}&nbspAr</h4>
        </div>
    </div>
</div>

templates/boutique/dependancies/_index_menu.html.twig
<li >
    <a class="active main-menu-link"href="{{ path('shop')}}" target="_blank">Galerie Marchande</a>
</li>

{% for key, menu in allMenus %}
 
     <li class="has-dropdown has-megaitem">
          <a href="#" style="color: white">
           {{ key }}&nbsp<i class="fa fa-angle-down"></i></a>
                      <!-- Mega Menu -->
                      <div class="mega-menu">
                        <ul class="mega-menu-inner">
                     
                        <!-- Mega Menu Sub Link -->
                       {% for keyc, _category in menu %}
                              
                          <li class="mega-menu-item">
                            <a href="#" class="mega-menu-item-title"
                              >- &nbsp{{ _category['category']}}</a
                            >
                            <ul class="mega-menu-sub">
                            {% for keys,sous_category in _category['sous_category'] %}
                              <li id="{{ slugify(sous_category['name']) }}" class="echantillon_image">
                                <a href="#" class="h4_menu  itemlink">{{ sous_category['name']}}</a>
                                {#<ul class="">
                                
                                   <li><a href="#">option</a></li>
                               
                                </ul>
                                #}
                            </li>
                            {% endfor %}
                            
                            </ul>
                          </li>
                         {% endfor %}

                        </ul>
                      </div>
    </li>
{% endfor %}

templates/boutique/dependancies/_list.html.twig
{% for article in articles %}



	<div class="col-md-4 col-sm-4 col-xs-6 col-lg-3 " style="margin-top: 3px;">
		<div class="cart container_cart">
		    {{ promo(article.promo,article.price, article.pricePromo) }}
				{% 		
			        	set href = path('detail',{'id' : article.id,'slug' : article.price~"-"~article.name|slug('-') })
				 %}
				 {% 
				    	set addCart = true 
				 %}
            {% if article.externalDetail is defined and article.externalDetail is not same as("") %}
			     {% set href = article.externalDetail %}
				  {% 
				    	set addCart = false 
				 %}
			{% endif %}
			{# {% 
				    	set addCart = true 
				 %} #}
			<a href= {{ href }} target = "_blank">
				<div class="container_image">
					<img src="{{ asset('images/'~article.images[0].name)}}" alt="">
					
					{% if addCart %}
						<button class="add_cart_btn add_cart" data-id-article="{{ article.id }}">
						<i class="fa fa-shopping-cart"></i>&nbsp Ajouter au panier</button>
					{% endif %}
				</div>
			</a>

			<div class="detail">
				<div class="product-rating">
					{{ my_vote_twig(article.votes) }}
				</div>
				<h1 class="product-name">{{article.name}}</h1>
				<h4 class="product-price">
					{% if article.price is same as(0)  %}
					    <span></span>
					{% else %}
				         {% if article.promo is same as('Promo')%}
							 {{article.pricePromo| number_format(0,',',' ') }}&nbspAr
							 <span class='old-prix'>{{article.price| number_format(0,',',' ') }}&nbspAr</span>
						 {% else %}
						 	{{article.price| number_format(0,',',' ') }}&nbspAr
						 {% endif %}
					{% endif %}

				</h4>

			</div>
			{#
			           {% if app.user %}
			                   {% if isWish(article.carts, app.user)=="true" %}
			                           <button class="_wish-btn wish-btn delete_wish" data-id-cart = "{{ article.carts[0].id }}" data-id-article="{{ article.id }}">
			                                   <i class="fa fa-heart"></i>
			                           </button>
			                           
			                   {% else %}
			                           <button class="_wish-btn wish-btn add_wish"  data-id-article="{{ article.id }}">
			                                   <i class="fa fa-heart-o"></i>
			                           </button>
			                   {% endif %}
			                   <button class="_cart-btn add_cart" data-id-article="{{ article.id }}">
			                        <i class="fa fa-shopping-cart"></i>
			                  </button>
			            {% else %}
			                   <button class="wish-btn _connexion" >
			                           <i class="fa fa-heart-o"></i>
			                   </button>
			                   <button class="_cart-btn _connexion" >
			                        <i class="fa fa-shopping-cart"></i>
			                  </button>
			           {% endif %}
			          #}
		</div>
	</div>
{% endfor %}

templates/boutique/dependancies/_list_comment_review_blog.html.twig
	<div id="reviews">
		<ul class="reviews">
		    {% if votes| length > 0 %}
				<label class="title_C">
					<a data-toggle="tab" href="#tab1">Listes des commentaires  ( {{ votes| length }} ) </a>
				</label>
			{% for vote in votes %}
				<li id="li-review-{{vote.id}}" class="li-review">
					<div class="review-heading">
						<div class="container_image_user_vote">
							<img src="{{asset('images/'~vote.user.avatar)}}" />
							<h5 class="name">{{ vote.user.name}}</h5>
						</div>
						
						<p class="date">{{vote.createdAt|date}}</p>
						<div class="review-rating">
							{{my_vote_twig(vote.value)}}
						</div>
					</div>
					<div class="review-body">
						<p>{{ vote.comment}}</p>
					</div>
					
					{% if app.user is not same as(null) and 'ROLE_SUPER_ADMIN' in app.user.roles or vote.user is same as(app.user) %}
						<button class="js-delete-vote delete-vote btn btn-danger" data-id="{{vote.id}}">Supprimer</button>
					{% endif %}

				</li>
			{% endfor %}
			{% endif %}
		</ul>
	</div>

templates/boutique/dependancies/_rating.html.twig
<div id="rating">
	<div class="rating-avg">
		{% set totalVote = votes|length==0 ? 1 : votes|length %}
		<span>{{ (valuevote['total']/ totalVote) | number_format(1,'.',' ') }}</span>
		<div class="rating-stars">
			{{my_vote_twig(votes)}}
		</div>
	</div>
	<ul class="rating">
		<li>
			<div class="rating-stars">
				{{ my_vote_twig(5) }}

			</div>
			<div class="rating-progress">
				<div style="width: {{ valuevote['five']/totalVote*100}}%"></div>
			</div>
			<span class="sum">{{valuevote['five']}}</span>
		</li>
		<li>
			<div class="rating-stars">
				{{ my_vote_twig(4) }}
			</div>
			<div class="rating-progress">
				<div style="width: {{ valuevote['four']/totalVote*100}}%"></div>
			</div>
			<span class="sum">{{valuevote['four']}}</span>
		</li>
		<li>
			<div class="rating-stars">
				{{ my_vote_twig(3) }}
			</div>
			<div class="rating-progress">
				<div style="width: {{ valuevote['tree']/totalVote*100}}%"></div>
			</div>
			<span class="sum">{{valuevote['tree']}}</span>
		</li>
		<li>
			<div class="rating-stars">
				{{ my_vote_twig(2) }}
			</div>
			<div class="rating-progress">
				<div style="width: {{ valuevote['two']/totalVote*100}}%"></div>
			</div>
			<span class="sum">{{valuevote['two']}}</span>
		</li>
		<li>
			<div class="rating-stars">
				{{ my_vote_twig(1) }}
			</div>
			<div class="rating-progress">
				<div style="width: {{ valuevote['one']/totalVote*100}}%"></div>
			</div>
			<span class="sum">{{valuevote['one']}}</span>
		</li>
	</ul>
</div>

templates/boutique/dependancies/header.html.twig
<header>
    <!-- TOP HEADER -->
    <!--div id="top-header">
        <div class="container">
            <ul class="header-cordinate">
                <li><a href="#"><i class="fa fa-phone"></i>  {{ boutique.contact}}</a></li>
                <li style="margin-left: 11px;margin-right: 11px;"><a href="#"><i class="fa fa-envelope-o"></i>  {{ boutique.mail}}</a></li>
                <li><a href="#"><i class="fa fa-map-marker"></i>  {{ boutique.address}}</a></li>
            </ul>
        </div>
    </div-->
    <!-- /TOP HEADER -->

    <!-- MAIN HEADER -->
     <div id='list_shop'>
     </div>
    <div id="header" style="display: grid;justify-content: space-between; align-items: center;grid-template-columns: 2fr 4fr 1fr;">
        <!-- container -->
        
            <!-- row -->
            
                <!-- LOGO -->
                <div class="">
                    <div class="header-logo">
                        <a href="{{ path('shop',{  })}}" class="logo">
                            <img  src="{{asset('images/'~boutique.logo)}}" alt="">
                        </a>
                      <span class="shop_name" style="color:white !important"> {{boutique.name}} <br> 
                    </div>
                </div>
                <!-- /LOGO -->

                <!-- SEARCH BAR -->

                {% include "boutique/dependancies/headersearch.html.twig" %}             
               
                <!-- /SEARCH BAR -->

                <!-- ACCOUNT -->
                 {% include "boutique/dependancies/_actionUser.html.twig"%}
                <!-- /ACCOUNT -->
           
            <!-- row -->
        
        <!-- container -->
    </div>
    <div class="inother-ajax">
        <div class="div-inother"></div>
    </div>
    <!-- /MAIN HEADER -->
</header>

templates/boutique/dependancies/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navigation">
                              
    <div class="collapse navbar-collapse" id="responsive-nav">
      <ul class="navbar-nav mr-auto main-nav ">
        <li class="nav-item active">
          <a class="nav-link" href="#">Accueil <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
    </li>
      </ul>
    </div>
  </nav>

templates/boutique/dependancies/newsletter.html.twig
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                    <form>
                        <input class="input" type="email" placeholder="Enter Your Email">
                        <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                    </form>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>